// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "HeroRegenData.generated.h"

/**
 * 
 */
USTRUCT(BlueprintType)
struct FHeroRegenData
{
	GENERATED_BODY()
public:
	FHeroRegenData() {}

	// Health regenerated by the hero per second.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hero Regen Data")
	float healthRegen;

	// The mana regenerated by the hero per second
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hero Regen Data")
	float manaRegen;
};
